from ProxXML import RawData, load_from_xml
from ProxMEL import maya_mel_create_scene
from ProxMayaAPI import maya_api_create_scene
import maya.standalone
import maya.cmds as cmds


if __name__ == '__main__':

    maya.standalone.initialize()


    cmds.file(force=True, new=True)
    cmds.file(rename='/Users/kenny/Documents/PROX_PAPERS/2017_CHUNKED_BVH/2017_RESULTS/raw_data/colosseum_w8100/tst.ma')
    cmds.file(force=True, type='mayaAscii', save=True)
    data = RawData()
    load_from_xml('/Users/kenny/Documents/PROX_PAPERS/2017_CHUNKED_BVH/2017_RESULTS/raw_data/colosseum_w8100/scene.xml',data, True)
    load_from_xml('/Users/kenny/Documents/PROX_PAPERS/2017_CHUNKED_BVH/2017_RESULTS/raw_data/colosseum_w8100/channels.xml',data, True)
    maya_api_create_scene(data)
    cmds.file(force=True, type='mayaAscii', save=True)




    # cmds.file(force=True, new=True)
    # cmds.file(rename='/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/gs_blocked_glasses_in_glass.ma')
    # cmds.file(force=True, type='mayaAscii', save=True)
    # data = RawData()
    # load_from_xml('/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/gs_blocked_glasses_in_glass_scene.xml', data, True)
    # load_from_xml('/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/gs_blocked_glasses_in_glass_channels.xml', data, True)
    # maya_api_create_scene(data)
    # cmds.file(force=True, type='mayaAscii', save=True)
    #
    #
    # cmds.file(force=True, new=True)
    # cmds.file(rename='/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/gs_blocked_jacks_in_glass.ma')
    # cmds.file(force=True, type='mayaAscii', save=True)
    # data = RawData()
    # load_from_xml('/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/gs_blocked_jacks_in_glass_scene.xml', data, True)
    # load_from_xml('/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/gs_blocked_jacks_in_glass_channels.xml', data, True)
    # maya_api_create_scene(data)
    # cmds.file(force=True, type='mayaAscii', save=True)
    #
    # cmds.file(force=True, new=True)
    # cmds.file(rename='/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/gs_blocked_spheres_in_glass.ma')
    # cmds.file(force=True, type='mayaAscii', save=True)
    # data = RawData()
    # load_from_xml('/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/gs_blocked_spheres_in_glass_scene.xml', data, True)
    # load_from_xml('/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/gs_blocked_spheres_in_glass_channels.xml', data, True)
    # maya_api_create_scene(data)
    # cmds.file(force=True, type='mayaAscii', save=True)
    #
    # cmds.file(force=True, new=True)
    # cmds.file(rename='/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/gs_blocked_tower.ma')
    # cmds.file(force=True, type='mayaAscii', save=True)
    # data = RawData()
    # load_from_xml('/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/gs_blocked_tower_scene.xml', data, True)
    # load_from_xml('/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/gs_blocked_tower_channels.xml', data, True)
    # maya_api_create_scene(data)
    # cmds.file(force=True, type='mayaAscii', save=True)
    #
    # cmds.file(force=True, new=True)
    # cmds.file(rename='/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/gs_blocked_wall.ma')
    # cmds.file(force=True, type='mayaAscii', save=True)
    # data = RawData()
    # load_from_xml('/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/gs_blocked_wall_scene.xml', data, True)
    # load_from_xml('/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/gs_blocked_wall_channels.xml', data, True)
    # maya_api_create_scene(data)
    # cmds.file(force=True, type='mayaAscii', save=True)
    #
    # cmds.file(force=True, new=True)
    # cmds.file(rename='/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/gs_bounce_spheres_in_glass.ma')
    # cmds.file(force=True, type='mayaAscii', save=True)
    # data = RawData()
    # load_from_xml('/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/gs_bounce_spheres_in_glass_scene.xml', data, True)
    # load_from_xml('/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/gs_bounce_spheres_in_glass_channels.xml', data, True)
    # maya_api_create_scene(data)
    # cmds.file(force=True, type='mayaAscii', save=True)
    #
    # cmds.file(force=True, new=True)
    # cmds.file(rename='/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/gs_bounce_tower.ma')
    # cmds.file(force=True, type='mayaAscii', save=True)
    # data = RawData()
    # load_from_xml('/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/gs_bounce_tower_scene.xml', data, True)
    # load_from_xml('/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/gs_bounce_tower_channels.xml', data, True)
    # maya_api_create_scene(data)
    # cmds.file(force=True, type='mayaAscii', save=True)
    #
    # cmds.file(force=True, new=True)
    # cmds.file(rename='/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/gs_bounce_wall.ma')
    # cmds.file(force=True, type='mayaAscii', save=True)
    # data = RawData()
    # load_from_xml('/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/gs_bounce_wall_scene.xml', data, True)
    # load_from_xml('/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/gs_bounce_wall_channels.xml', data, True)
    # maya_api_create_scene(data)
    # cmds.file(force=True, type='mayaAscii', save=True)
    #
    # cmds.file(force=True, new=True)
    # cmds.file(rename='/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/gs_box_model_spheres_in_glass.ma')
    # cmds.file(force=True, type='mayaAscii', save=True)
    # data = RawData()
    # load_from_xml('/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/gs_box_model_spheres_in_glass_scene.xml', data, True)
    # load_from_xml('/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/gs_box_model_spheres_in_glass_channels.xml', data, True)
    # maya_api_create_scene(data)
    # cmds.file(force=True, type='mayaAscii', save=True)
    #
    # cmds.file(force=True, new=True)
    # cmds.file(rename='/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/gs_box_model_jacks_in_glass.ma')
    # cmds.file(force=True, type='mayaAscii', save=True)
    # data = RawData()
    # load_from_xml('/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/gs_box_model_jacks_in_glass_scene.xml', data, True)
    # load_from_xml('/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/gs_box_model_jacks_in_glass_channels.xml', data, True)
    # maya_api_create_scene(data)
    # cmds.file(force=True, type='mayaAscii', save=True)
    #
    # cmds.file(force=True, new=True)
    # cmds.file(rename='/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/gs_box_model_pantheon.ma')
    # cmds.file(force=True, type='mayaAscii', save=True)
    # data = RawData()
    # load_from_xml('/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/gs_box_model_pantheon_scene.xml', data, True)
    # load_from_xml('/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/gs_box_model_pantheon_channels.xml', data, True)
    # maya_api_create_scene(data)
    # cmds.file(force=True, type='mayaAscii', save=True)
    #
    # cmds.file(force=True, new=True)
    # cmds.file(rename='/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/gs_box_model_tower.ma')
    # cmds.file(force=True, type='mayaAscii', save=True)
    # data = RawData()
    # load_from_xml('/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/gs_box_model_tower_scene.xml', data, True)
    # load_from_xml('/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/gs_box_model_tower_channels.xml', data, True)
    # maya_api_create_scene(data)
    # cmds.file(force=True, type='mayaAscii', save=True)
    #
    # cmds.file(force=True, new=True)
    # cmds.file(rename='/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/gs_box_model_wall.ma')
    # cmds.file(force=True, type='mayaAscii', save=True)
    # data = RawData()
    # load_from_xml('/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/gs_box_model_wall_scene.xml', data, True)
    # load_from_xml('/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/gs_box_model_wall_channels.xml', data, True)
    # maya_api_create_scene(data)
    # cmds.file(force=True, type='mayaAscii', save=True)
    #
    # cmds.file(force=True, new=True)
    # cmds.file(rename='/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/gs_global_glasses_in_glass.ma')
    # cmds.file(force=True, type='mayaAscii', save=True)
    # data = RawData()
    # load_from_xml('/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/gs_global_glasses_in_glass_scene.xml', data, True)
    # load_from_xml('/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/gs_global_glasses_in_glass_channels.xml', data, True)
    # maya_api_create_scene(data)
    # cmds.file(force=True, type='mayaAscii', save=True)
    #
    # cmds.file(force=True, new=True)
    # cmds.file(rename='/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/gs_global_jacks_in_glass.ma')
    # cmds.file(force=True, type='mayaAscii', save=True)
    # data = RawData()
    # load_from_xml('/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/gs_global_jacks_in_glass_scene.xml', data, True)
    # load_from_xml('/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/gs_global_jacks_in_glass_channels.xml', data, True)
    # maya_api_create_scene(data)
    # cmds.file(force=True, type='mayaAscii', save=True)
    #
    # cmds.file(force=True, new=True)
    # cmds.file(rename='/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/gs_global_spheres_in_glass.ma')
    # cmds.file(force=True, type='mayaAscii', save=True)
    # data = RawData()
    # load_from_xml('/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/gs_global_spheres_in_glass_scene.xml', data, True)
    # load_from_xml('/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/gs_global_spheres_in_glass_channels.xml', data, True)
    # maya_api_create_scene(data)
    # cmds.file(force=True, type='mayaAscii', save=True)
    #
    # cmds.file(force=True, new=True)
    # cmds.file(rename='/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/gs_global_tower.ma')
    # cmds.file(force=True, type='mayaAscii', save=True)
    # data = RawData()
    # load_from_xml('/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/gs_global_tower_scene.xml', data, True)
    # load_from_xml('/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/gs_global_tower_channels.xml', data, True)
    # maya_api_create_scene(data)
    # cmds.file(force=True, type='mayaAscii', save=True)
    #
    # cmds.file(force=True, new=True)
    # cmds.file(rename='/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/gs_global_wall.ma')
    # cmds.file(force=True, type='mayaAscii', save=True)
    # data = RawData()
    # load_from_xml('/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/gs_global_wall_scene.xml', data, True)
    # load_from_xml('/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/gs_global_wall_channels.xml', data, True)
    # maya_api_create_scene(data)
    # cmds.file(force=True, type='mayaAscii', save=True)
    #
    # cmds.file(force=True, new=True)
    # cmds.file(rename='/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/gs_local_colosseum.ma')
    # cmds.file(force=True, type='mayaAscii', save=True)
    # data = RawData()
    # load_from_xml('/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/gs_local_colosseum_scene.xml', data, True)
    # load_from_xml('/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/gs_local_colosseum_channels.xml', data, True)
    # maya_api_create_scene(data)
    # cmds.file(force=True, type='mayaAscii', save=True)
    #
    # cmds.file(force=True, new=True)
    # cmds.file(rename='/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/gs_local_glasses_in_glass.ma')
    # cmds.file(force=True, type='mayaAscii', save=True)
    # data = RawData()
    # load_from_xml('/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/gs_local_glasses_in_glass_scene.xml', data, True)
    # load_from_xml('/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/gs_local_glasses_in_glass_channels.xml', data, True)
    # maya_api_create_scene(data)
    # cmds.file(force=True, type='mayaAscii', save=True)
    #
    # cmds.file(force=True, new=True)
    # cmds.file(rename='/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/gs_local_jacks_in_funnel.ma')
    # cmds.file(force=True, type='mayaAscii', save=True)
    # data = RawData()
    # load_from_xml('/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/gs_local_jacks_in_funnel_scene.xml', data, True)
    # load_from_xml('/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/gs_local_jacks_in_funnel_channels.xml', data, True)
    # maya_api_create_scene(data)
    # cmds.file(force=True, type='mayaAscii', save=True)
    #
    # cmds.file(force=True, new=True)
    # cmds.file(rename='/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/gs_local_jacks_in_glass.ma')
    # cmds.file(force=True, type='mayaAscii', save=True)
    # data = RawData()
    # load_from_xml('/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/gs_local_jacks_in_glass_scene.xml', data, True)
    # load_from_xml('/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/gs_local_jacks_in_glass_channels.xml', data, True)
    # maya_api_create_scene(data)
    # cmds.file(force=True, type='mayaAscii', save=True)
    #
    # cmds.file(force=True, new=True)
    # cmds.file(rename='/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/gs_local_pantheon.ma')
    # cmds.file(force=True, type='mayaAscii', save=True)
    # data = RawData()
    # load_from_xml('/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/gs_local_pantheon_scene.xml', data, True)
    # load_from_xml('/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/gs_local_pantheon_channels.xml', data, True)
    # maya_api_create_scene(data)
    # cmds.file(force=True, type='mayaAscii', save=True)
    #
    # cmds.file(force=True, new=True)
    # cmds.file(rename='/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/gs_local_shoot.ma')
    # cmds.file(force=True, type='mayaAscii', save=True)
    # data = RawData()
    # load_from_xml('/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/gs_local_shoot_scene.xml', data, True)
    # load_from_xml('/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/gs_local_shoot_channels.xml', data, True)
    # maya_api_create_scene(data)
    # cmds.file(force=True, type='mayaAscii', save=True)
    #
    # cmds.file(force=True, new=True)
    # cmds.file(rename='/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/gs_local_spheres_in_glass.ma')
    # cmds.file(force=True, type='mayaAscii', save=True)
    # data = RawData()
    # load_from_xml('/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/gs_local_spheres_in_glass_scene.xml', data, True)
    # load_from_xml('/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/gs_local_spheres_in_glass_channels.xml', data, True)
    # maya_api_create_scene(data)
    # cmds.file(force=True, type='mayaAscii', save=True)
    #
    # cmds.file(force=True, new=True)
    # cmds.file(rename='/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/gs_local_temple.ma')
    # cmds.file(force=True, type='mayaAscii', save=True)
    # data = RawData()
    # load_from_xml('/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/gs_local_temple_scene.xml', data, True)
    # load_from_xml('/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/gs_local_temple_channels.xml', data, True)
    # maya_api_create_scene(data)
    # cmds.file(force=True, type='mayaAscii', save=True)
    #
    # cmds.file(force=True, new=True)
    # cmds.file(rename='/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/gs_local_tower.ma')
    # cmds.file(force=True, type='mayaAscii', save=True)
    # data = RawData()
    # load_from_xml('/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/gs_local_tower_scene.xml', data, True)
    # load_from_xml('/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/gs_local_tower_channels.xml', data, True)
    # maya_api_create_scene(data)
    # cmds.file(force=True, type='mayaAscii', save=True)

    #cmds.file(force=True, new=True)
    #cmds.file(rename='/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/gs_local_wall.ma')
    #cmds.file(force=True, type='mayaAscii', save=True)
    #data = RawData()
    #load_from_xml('/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/gs_local_wall_scene.xml', data, True)
    #load_from_xml('/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/gs_local_wall_channels.xml', data, True)
    #maya_api_create_scene(data)
    #cmds.file(force=True, type='mayaAscii', save=True)

    # cmds.file(force=True, new=True)
    # cmds.file(rename='/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/gs_no_friction_glasses_in_glass.ma')
    # cmds.file(force=True, type='mayaAscii', save=True)
    # data = RawData()
    # load_from_xml('/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/gs_no_friction_glasses_in_glass_scene.xml', data, True)
    # load_from_xml('/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/gs_no_friction_glasses_in_glass_channels.xml', data, True)
    # maya_api_create_scene(data)
    # cmds.file(force=True, type='mayaAscii', save=True)
    #
    # cmds.file(force=True, new=True)
    # cmds.file(rename='/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/gs_no_friction_jacks_in_glass.ma')
    # cmds.file(force=True, type='mayaAscii', save=True)
    # data = RawData()
    # load_from_xml('/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/gs_no_friction_jacks_in_glass_scene.xml', data, True)
    # load_from_xml('/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/gs_no_friction_jacks_in_glass_channels.xml', data, True)
    # maya_api_create_scene(data)
    # cmds.file(force=True, type='mayaAscii', save=True)
    #
    # cmds.file(force=True, new=True)
    # cmds.file(rename='/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/gs_no_friction_spheres_in_glass.ma')
    # cmds.file(force=True, type='mayaAscii', save=True)
    # data = RawData()
    # load_from_xml('/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/gs_no_friction_spheres_in_glass_scene.xml', data, True)
    # load_from_xml('/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/gs_no_friction_spheres_in_glass_channels.xml', data, True)
    # maya_api_create_scene(data)
    # cmds.file(force=True, type='mayaAscii', save=True)
    #
    # cmds.file(force=True, new=True)
    # cmds.file(rename='/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/gs_no_friction_tower.ma')
    # cmds.file(force=True, type='mayaAscii', save=True)
    # data = RawData()
    # load_from_xml('/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/gs_no_friction_tower_scene.xml', data, True)
    # load_from_xml('/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/gs_no_friction_tower_channels.xml', data, True)
    # maya_api_create_scene(data)
    # cmds.file(force=True, type='mayaAscii', save=True)
    #
    # cmds.file(force=True, new=True)
    # cmds.file(rename='/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/gs_no_friction_wall.ma')
    # cmds.file(force=True, type='mayaAscii', save=True)
    # data = RawData()
    # load_from_xml('/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/gs_no_friction_wall_scene.xml', data, True)
    # load_from_xml('/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/gs_no_friction_wall_channels.xml', data, True)
    # maya_api_create_scene(data)
    # cmds.file(force=True, type='mayaAscii', save=True)
    #
    # cmds.file(force=True, new=True)
    # cmds.file(rename='/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/gs_no_stab_glasses_in_glass.ma')
    # cmds.file(force=True, type='mayaAscii', save=True)
    # data = RawData()
    # load_from_xml('/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/gs_no_stab_glasses_in_glass_scene.xml', data, True)
    # load_from_xml('/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/gs_no_stab_glasses_in_glass_channels.xml', data, True)
    # maya_api_create_scene(data)
    # cmds.file(force=True, type='mayaAscii', save=True)
    #
    # cmds.file(force=True, new=True)
    # cmds.file(rename='/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/gs_no_stab_jacks_in_glass.ma')
    # cmds.file(force=True, type='mayaAscii', save=True)
    # data = RawData()
    # load_from_xml('/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/gs_no_stab_jacks_in_glass_scene.xml', data, True)
    # load_from_xml('/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/gs_no_stab_jacks_in_glass_channels.xml', data, True)
    # maya_api_create_scene(data)
    # cmds.file(force=True, type='mayaAscii', save=True)
    #
    # cmds.file(force=True, new=True)
    # cmds.file(rename='/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/gs_no_stab_spheres_in_glass.ma')
    # cmds.file(force=True, type='mayaAscii', save=True)
    # data = RawData()
    # load_from_xml('/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/gs_no_stab_spheres_in_glass_scene.xml', data, True)
    # load_from_xml('/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/gs_no_stab_spheres_in_glass_channels.xml', data, True)
    # maya_api_create_scene(data)
    # cmds.file(force=True, type='mayaAscii', save=True)
    #
    # cmds.file(force=True, new=True)
    # cmds.file(rename='/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/gs_no_stab_tower.ma')
    # cmds.file(force=True, type='mayaAscii', save=True)
    # data = RawData()
    # load_from_xml('/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/gs_no_stab_tower_scene.xml', data, True)
    # load_from_xml('/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/gs_no_stab_tower_channels.xml', data, True)
    # maya_api_create_scene(data)
    # cmds.file(force=True, type='mayaAscii', save=True)
    #
    # cmds.file(force=True, new=True)
    # cmds.file(rename='/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/gs_no_stab_wall.ma')
    # cmds.file(force=True, type='mayaAscii', save=True)
    # data = RawData()
    # load_from_xml('/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/gs_no_stab_wall_scene.xml', data, True)
    # load_from_xml('/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/gs_no_stab_wall_channels.xml', data, True)
    # maya_api_create_scene(data)
    # cmds.file(force=True, type='mayaAscii', save=True)
    #
    # cmds.file(force=True, new=True)
    # cmds.file(rename='/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/gs_pre_post_glasses_in_glass.ma')
    # cmds.file(force=True, type='mayaAscii', save=True)
    # data = RawData()
    # load_from_xml('/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/gs_pre_post_glasses_in_glass_scene.xml', data, True)
    # load_from_xml('/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/gs_pre_post_glasses_in_glass_channels.xml', data, True)
    # maya_api_create_scene(data)
    # cmds.file(force=True, type='mayaAscii', save=True)
    #
    # cmds.file(force=True, new=True)
    # cmds.file(rename='/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/gs_pre_post_jacks_in_glass.ma')
    # cmds.file(force=True, type='mayaAscii', save=True)
    # data = RawData()
    # load_from_xml('/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/gs_pre_post_jacks_in_glass_scene.xml', data, True)
    # load_from_xml('/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/gs_pre_post_jacks_in_glass_channels.xml', data, True)
    # maya_api_create_scene(data)
    # cmds.file(force=True, type='mayaAscii', save=True)
    #
    # cmds.file(force=True, new=True)
    # cmds.file(rename='/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/gs_pre_post_spheres_in_glass.ma')
    # cmds.file(force=True, type='mayaAscii', save=True)
    # data = RawData()
    # load_from_xml('/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/gs_pre_post_spheres_in_glass_scene.xml', data, True)
    # load_from_xml('/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/gs_pre_post_spheres_in_glass_channels.xml', data, True)
    # maya_api_create_scene(data)
    # cmds.file(force=True, type='mayaAscii', save=True)
    #
    # cmds.file(force=True, new=True)
    # cmds.file(rename='/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/gs_pre_post_tower.ma')
    # cmds.file(force=True, type='mayaAscii', save=True)
    # data = RawData()
    # load_from_xml('/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/gs_pre_post_tower_scene.xml', data, True)
    # load_from_xml('/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/gs_pre_post_tower_channels.xml', data, True)
    # maya_api_create_scene(data)
    # cmds.file(force=True, type='mayaAscii', save=True)
    #
    # cmds.file(force=True, new=True)
    # cmds.file(rename='/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/gs_pre_post_wall.ma')
    # cmds.file(force=True, type='mayaAscii', save=True)
    # data = RawData()
    # load_from_xml('/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/gs_pre_post_wall_scene.xml', data, True)
    # load_from_xml('/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/gs_pre_post_wall_channels.xml', data, True)
    # maya_api_create_scene(data)
    # cmds.file(force=True, type='mayaAscii', save=True)
    #
    # cmds.file(force=True, new=True)
    # cmds.file(rename='/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/jacobi_pre_post_spheres_in_glass.ma')
    # cmds.file(force=True, type='mayaAscii', save=True)
    # data = RawData()
    # load_from_xml('/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/jacobi_pre_post_spheres_in_glass_scene.xml', data, True)
    # load_from_xml('/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/jacobi_pre_post_spheres_in_glass_channels.xml', data, True)
    # maya_api_create_scene(data)
    # cmds.file(force=True, type='mayaAscii', save=True)
    #
    # cmds.file(force=True, new=True)
    # cmds.file(rename='/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/long_runs_glasses_in_glass.ma')
    # cmds.file(force=True, type='mayaAscii', save=True)
    # data = RawData()
    # load_from_xml('/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/long_runs_glasses_in_glass_scene.xml', data, True)
    # load_from_xml('/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/long_runs_glasses_in_glass_channels.xml', data, True)
    # maya_api_create_scene(data)
    # cmds.file(force=True, type='mayaAscii', save=True)
    #
    # cmds.file(force=True, new=True)
    # cmds.file(rename='/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/long_runs_jacks_in_funnel.ma')
    # cmds.file(force=True, type='mayaAscii', save=True)
    # data = RawData()
    # load_from_xml('/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/long_runs_jacks_in_funnel_scene.xml', data, True)
    # load_from_xml('/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/long_runs_jacks_in_funnel_channels.xml', data, True)
    # maya_api_create_scene(data)
    # cmds.file(force=True, type='mayaAscii', save=True)
    #
    # cmds.file(force=True, new=True)
    # cmds.file(rename='/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/long_runs_jacks_in_glass.ma')
    # cmds.file(force=True, type='mayaAscii', save=True)
    # data = RawData()
    # load_from_xml('/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/long_runs_jacks_in_glass_scene.xml', data, True)
    # load_from_xml('/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/long_runs_jacks_in_glass_channels.xml', data, True)
    # maya_api_create_scene(data)
    # cmds.file(force=True, type='mayaAscii', save=True)
    #
    # cmds.file(force=True, new=True)
    # cmds.file(rename='/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/long_runs_pantheon.ma')
    # cmds.file(force=True, type='mayaAscii', save=True)
    # data = RawData()
    # load_from_xml('/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/long_runs_pantheon_scene.xml', data, True)
    # load_from_xml('/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/long_runs_pantheon_channels.xml', data, True)
    # maya_api_create_scene(data)
    # cmds.file(force=True, type='mayaAscii', save=True)
    #
    # cmds.file(force=True, new=True)
    # cmds.file(rename='/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/long_runs_shoot.ma')
    # cmds.file(force=True, type='mayaAscii', save=True)
    # data = RawData()
    # load_from_xml('/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/long_runs_shoot_scene.xml', data, True)
    # load_from_xml('/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/long_runs_shoot_channels.xml', data, True)
    # maya_api_create_scene(data)
    # cmds.file(force=True, type='mayaAscii', save=True)
    #
    # cmds.file(force=True, new=True)
    # cmds.file(rename='/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/long_runs_spheres_in_glass.ma')
    # cmds.file(force=True, type='mayaAscii', save=True)
    # data = RawData()
    # load_from_xml('/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/long_runs_spheres_in_glass_scene.xml', data, True)
    # load_from_xml('/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/long_runs_spheres_in_glass_channels.xml', data, True)
    # maya_api_create_scene(data)
    # cmds.file(force=True, type='mayaAscii', save=True)
    #
    # cmds.file(force=True, new=True)
    # cmds.file(rename='/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/long_runs_tower.ma')
    # cmds.file(force=True, type='mayaAscii', save=True)
    # data = RawData()
    # load_from_xml('/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/long_runs_tower_scene.xml', data, True)
    # load_from_xml('/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/long_runs_tower_channels.xml', data, True)
    # maya_api_create_scene(data)
    # cmds.file(force=True, type='mayaAscii', save=True)
    #
    # cmds.file(force=True, new=True)
    # cmds.file(rename='/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/long_runs_wall.ma')
    # cmds.file(force=True, type='mayaAscii', save=True)
    # data = RawData()
    # load_from_xml('/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/long_runs_wall_scene.xml', data, True)
    # load_from_xml('/Users/kenny/Documents/PROX_PAPERS/2017_SCA_PROX/2017_RESULTS/2017_03_22/long_runs_wall_channels.xml', data, True)
    # maya_api_create_scene(data)
    # cmds.file(force=True, type='mayaAscii', save=True)

    maya.standalone.uninitialize()
