ADD_SUBDIRECTORY(grid_test_grid)
ADD_SUBDIRECTORY(grid_local_strategy)
ADD_SUBDIRECTORY(grid_local_optimization_gradient)
ADD_SUBDIRECTORY(grid_local_optimization_test_GSS_minimize)
ADD_SUBDIRECTORY(grid_local_optimization_FWGSS)
ADD_SUBDIRECTORY(grid_local_optimization_FWGSS_Stress_Test)
ADD_SUBDIRECTORY(grid_local_optimization_FWGSS_TOI_STRESSER)
